# Generated by Django 4.1.2 on 2022-11-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Nome da marca')),
                ('foundation_Date', models.DateTimeField(verbose_name='Data de Fundação')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200, verbose_name='Nome do carro')),
                ('value_car', models.IntegerField(default=0, verbose_name='Valor do carro')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrinho.brand')),
            ],
        ),
    ]
